version: '3'

services:
  nexus:
    image: sonatype/nexus3
    ports:
      - '8081:8081'
    volumes:
      - nexus-data:/nexus-data

  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - '9000:9000'
    volumes:
      - sonarqube-data:/opt/sonarqube1/data
      - sonarqube-logs:/opt/sonarqube1/logs
      - sonarqube-extensions:/opt/sonarqube1/extensions
      - ./plugins:/opt/sonarqube1/extensions/plugins

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - monitoring

volumes:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
  nexus-data:

networks:
  monitoring: