version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD:'yes'
      MYSQL_DATABASE:achat
    ports:
      - "3306:3306"
  achat:
    image: nourelhoudal/achat:1.0.0
    ports:
      - "8090:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb
      SPRING_DATASOURCE_USERNAME: root

