version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    volumes:
      - ./logstash/config:/usr/share/logstash/config
    command: logstash -f /usr/share/logstash/config/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=achat
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

  achat:
    container_name: achatback
    depends_on:
      - mysqldb
    build: 
      context: ./
      args:
        - "BUILD_NO_CACHE=--no-cache"
    image: aymenmz/achatback:1.0.0
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://mysqldb:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" :  "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
